// Generated by CoffeeScript 1.10.0
var Events, FormView, LineItem, crowdcontrol, input,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

crowdcontrol = require('crowdcontrol');

Events = crowdcontrol.Events;

FormView = crowdcontrol.view.form.FormView;

input = require('../utils/input');

LineItem = (function(superClass) {
  extend(LineItem, superClass);

  function LineItem() {
    return LineItem.__super__.constructor.apply(this, arguments);
  }

  LineItem.prototype.tag = 'lineitem';

  LineItem.prototype.html = require('../../templates/lineitem.jade');

  LineItem.prototype.renderCurrency = require('../utils/currency').renderUICurrencyFromJSON;

  LineItem.prototype.inputConfigs = [input('quantity', '', 'quantity-select parsenumber')];

  LineItem.prototype.invoiceObs = null;

  LineItem.prototype.js = function(opts) {
    LineItem.__super__.js.apply(this, arguments);
    return this.currency = opts.currency;
  };

  return LineItem;

})(FormView);

LineItem.register();

module.exports = LineItem;

//# sourceMappingURL=lineitem.js.map
