// Generated by CoffeeScript 1.10.0
var Events, Tabs, View, crowdcontrol, input,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

crowdcontrol = require('crowdcontrol');

Events = crowdcontrol.Events;

View = crowdcontrol.view.View;

input = require('../utils/input');

Tabs = (function(superClass) {
  extend(Tabs, superClass);

  function Tabs() {
    return Tabs.__super__.constructor.apply(this, arguments);
  }

  Tabs.prototype.tag = 'tabs';

  Tabs.prototype.html = require('../../templates/tabs.jade');

  Tabs.prototype.selected = 'stripe';

  Tabs.prototype.chooseStripe = function() {
    this.selected = 'stripe';
    return this.obs.trigger(Events.Screen.Payment.ChooseStripe);
  };

  Tabs.prototype.choosePaypal = function() {
    this.selected = 'paypal';
    return this.obs.trigger(Events.Screen.Payment.ChoosePaypal);
  };

  return Tabs;

})(View);

Tabs.register();

module.exports = Tabs;

//# sourceMappingURL=tabs.js.map
