// Generated by CoffeeScript 1.10.0
var Events, View, Widget, crowdcontrol,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

crowdcontrol = require('crowdcontrol');

Events = crowdcontrol.Events;

View = crowdcontrol.view.View;

Widget = (function(superClass) {
  extend(Widget, superClass);

  function Widget() {
    return Widget.__super__.constructor.apply(this, arguments);
  }

  Widget.prototype.tag = 'widget';

  Widget.prototype.html = require('../../templates/widget.jade');

  Widget.prototype.js = function(opts) {
    return this.client = opts.client;
  };

  return Widget;

})(View);

Widget.register();

module.exports = Widget;

//# sourceMappingURL=widget.js.map
