// Generated by CoffeeScript 1.9.2
var ItemRef;

module.exports = ItemRef = (function() {
  function ItemRef(productId, quantity) {
    this.productId = productId;
    this.quantity = quantity != null ? quantity : 1;
    this.quantity = Math.min(Math.max(this.quantity, 1), 9);
  }

  return ItemRef;

})();

//# sourceMappingURL=itemRef.js.map
