// Generated by CoffeeScript 1.9.2
var Order;

module.exports = Order = (function() {
  function Order(currency, itemRefs, shippingAddress) {
    this.currency = currency;
    this.itemRefs = itemRefs;
    this.shippingAddress = shippingAddress != null ? shippingAddress : {
      country: 'us'
    };
    this.items = [];
  }

  return Order;

})();

//# sourceMappingURL=order.js.map
