// Generated by CoffeeScript 1.9.2
var Payment;

module.exports = Payment = (function() {
  function Payment() {
    this.type = 'stripe';
    this.account = {
      number: '',
      month: '',
      year: '',
      cvc: ''
    };
  }

  return Payment;

})();

//# sourceMappingURL=payment.js.map
