// Generated by CoffeeScript 1.9.2
var User;

module.exports = User = (function() {
  function User(email, firstName, lastName) {
    this.email = email != null ? email : '';
    this.firstName = firstName != null ? firstName : '';
    this.lastName = lastName != null ? lastName : '';
  }

  return User;

})();

//# sourceMappingURL=user.js.map
