// Generated by CoffeeScript 1.9.2
var View, riot;

riot = require('riot');

View = (function() {
  View.prototype.tag = 'view';

  View.prototype.html = '<div></div>';

  View.prototype.ctx = null;

  View.prototype.js = function() {};

  function View(tag, html, js) {
    var view;
    this.tag = tag;
    this.html = html;
    this.js = js;
    view = this;
    riot.tag(this.tag, this.html, function(opts) {
      this.view = view;
      this.opts = opts;
      view.ctx = this;
      if (view.js != null) {
        return view.js.call(this, opts, view);
      }
    });
  }

  View.prototype.update = function() {
    if (this.ctx != null) {
      return this.ctx.update();
    }
  };

  return View;

})();

module.exports = View;

//# sourceMappingURL=view.js.map
