// Generated by CoffeeScript 1.10.0
var Events, Screen, ThankYou, analytics, crowdcontrol,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

crowdcontrol = require('crowdcontrol');

Events = crowdcontrol.Events;

Screen = require('./screen');

analytics = require('../../utils/analytics');

ThankYou = (function(superClass) {
  extend(ThankYou, superClass);

  function ThankYou() {
    return ThankYou.__super__.constructor.apply(this, arguments);
  }

  ThankYou.prototype.tag = 'thankyou';

  ThankYou.prototype.title = 'Done!';

  ThankYou.prototype.html = require('../../../templates/screens/thankyou.jade');

  ThankYou.prototype.showConfirm = false;

  ThankYou.prototype.showBack = false;

  ThankYou.prototype.showInvoice = false;

  ThankYou.prototype._submit = function() {};

  ThankYou.prototype.show = function() {
    analytics.track('Viewed Checkout Step', {
      step: 3
    });
    return $('body').animate({
      scrollTop: $('screen-manager').first().offset().top - 50
    }, 500);
  };

  return ThankYou;

})(Screen);

ThankYou.register();

module.exports = ThankYou;

//# sourceMappingURL=thankyou.js.map
