// Generated by CoffeeScript 1.10.0
module.exports = {
  track: function(event, data) {
    if (window.analytics != null) {
      return window.analytics.track(event, data);
    }
  }
};

//# sourceMappingURL=analytics.js.map
