// Generated by CoffeeScript 1.9.2
module.exports = {
  showError: function(target, message, css) {
    var hover;
    if (css == null) {
      css = {};
    }
    hover = $(target).parent().children('.crowdstart-hover');
    if (hover[0] == null) {
      hover = $(target).parent().append('<div class="crowdstart-hover" style="opacity:0">').children('.crowdstart-hover');
      hover.append('<span class="crowdstart-message">');
      requestAnimationFrame(function() {
        return hover.removeAttr('style');
      });
    }
    return hover.closest('.crowdstart-form-control').addClass('crowdstart-error').find('.crowdstart-hover').removeClass('crowdstart-hidden').find('.crowdstart-message').text(message).css(css);
  },
  removeError: function(event) {
    var $el;
    $el = $(event.target).closest('.crowdstart-form-control').removeClass('crowdstart-error').find('.crowdstart-hover').addClass('crowdstart-hidden');
    return setTimeout(function() {
      return $el.remove();
    }, 500);
  },
  isRequired: function(text) {
    return text.length > 0;
  },
  isEmail: function(email) {
    return email.match(/[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/);
  }
};

//# sourceMappingURL=form.js.map
