// Generated by CoffeeScript 1.10.0
var InputConfig, crowdcontrol;

crowdcontrol = require('crowdcontrol');

InputConfig = crowdcontrol.view.form.InputConfig;

module.exports = function(name, placeholder, hints, value) {
  if (value == null) {
    value = '';
  }
  return new InputConfig(name, value, placeholder, hints);
};

//# sourceMappingURL=input.js.map
