// Generated by CoffeeScript 1.10.0
var util;

util = {
  isObject: function(obj) {
    var type;
    type = typeof obj;
    return type === 'function' || type === 'object' && !!obj;
  },
  isNumber: function(obj) {
    return toString.call(obj) === '[object Number]';
  }
};

module.exports = util;

//# sourceMappingURL=util.js.map
